# Generated by Django 5.0.6 on 2024-06-18 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appdev', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='text',
            new_name='content',
        ),
    ]
